// lib/order-items.js
// The one place that encodes a shop order's line items into Stripe metadata
// and decodes them back. Every writer (create-checkout-session) and every
// reader (webhook, admin feed, Evri export, stock sync, success-page summary)
// goes through here, so the format can only ever change in one file.
//
// Why this exists: Stripe caps each metadata value at 500 characters. The old
// format — one `items` value holding JSON `[{name, handle, size, qty}]` —
// overflowed at ~7 distinct lines and the whole checkout failed. The new format
// is compact tuples `[[handle, size, qty], …]` (names are looked up from the
// product map at read time, so renaming a product changes nothing) split across
// as many ≤500-char values as needed: `items`, `items_2`, `items_3`, …
//
// Stripe bounds this respects: value ≤ 500 chars, key ≤ 40 chars, ≤ 50 keys per
// object (the webhook/admin add ~13 more keys after checkout, so chunks are
// hard-capped at 12 — Stripe Checkout's own 100-line-item ceiling needs ~7).
//
// Decoding accepts BOTH formats, so the hundreds of historic orders already in
// Stripe keep working everywhere.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MAPPING_PATH = path.resolve(__dirname, '..', 'data', 'stripe-products.json');

export const METADATA_VALUE_MAX = 500; // Stripe: characters per metadata value
export const ITEMS_KEY = 'items';
export const ITEMS_MAX_CHUNKS = 12; // items, items_2 … items_12 (≈ 180 lines; Checkout allows 100)
export const CHECKOUT_MAX_LINES = 100; // Stripe Checkout: line_items per session
export const CUSTOM_TEXT_MAX = 1200; // Stripe: custom_text.*.message characters

let productMap = null;
// handle -> { productId, priceId, name, unitAmount, currency, clubPrices?, eur? }
// (data/stripe-products.json, generated by the website repo's scripts/stripe-sync.js
// and bundled with every backend deploy). Cached for the life of the function instance.
export function loadProductMap() {
  if (productMap) return productMap;
  productMap = JSON.parse(fs.readFileSync(MAPPING_PATH, 'utf8'));
  return productMap;
}

export function nameFor(handle) {
  try {
    return loadProductMap()[handle]?.name || handle;
  } catch {
    return handle;
  }
}

function chunkKey(i) {
  return i === 0 ? ITEMS_KEY : `${ITEMS_KEY}_${i + 1}`;
}

// lines: [{ handle, size, quantity|qty }] → { items, items_2, … }
// Each value is valid JSON on its own? No — only the concatenation is. Values are
// split on element boundaries so no tuple straddles a 500-char edge, which keeps
// the stored strings readable in the Stripe dashboard.
export function encodeItems(lines) {
  const tuples = lines.map((l) => [l.handle, l.size, Number(l.quantity ?? l.qty ?? 1) || 1]);
  const parts = tuples.map((t) => JSON.stringify(t));
  const chunks = [];
  let current = '[';
  parts.forEach((part, idx) => {
    const sep = idx === 0 ? '' : ',';
    const closing = idx === parts.length - 1 ? ']' : '';
    if (current.length + sep.length + part.length + closing.length > METADATA_VALUE_MAX) {
      chunks.push(current);
      current = '';
    }
    current += (current === '' ? (idx === 0 ? '[' : ',') : sep) + part + closing;
  });
  chunks.push(current);
  if (chunks.length > ITEMS_MAX_CHUNKS) {
    throw new Error(`Order has too many lines to record (${lines.length}); max ${ITEMS_MAX_CHUNKS} metadata chunks`);
  }
  const out = {};
  chunks.forEach((c, i) => { out[chunkKey(i)] = c; });
  return out;
}

// metadata → [{ name, handle, size, qty }]. Never throws: malformed/absent → [].
export function decodeItems(metadata) {
  if (!metadata || typeof metadata !== 'object') return [];
  let raw = '';
  for (let i = 0; i < ITEMS_MAX_CHUNKS; i++) {
    const v = metadata[chunkKey(i)];
    if (typeof v !== 'string' || v === '') break;
    raw += v;
  }
  if (!raw) return [];
  let parsed;
  try {
    parsed = JSON.parse(raw);
  } catch {
    return [];
  }
  if (!Array.isArray(parsed)) return [];
  return parsed
    .map((entry) => {
      if (Array.isArray(entry)) {
        // new compact tuple
        const [handle, size, qty] = entry;
        if (typeof handle !== 'string') return null;
        return { name: nameFor(handle), handle, size: typeof size === 'string' ? size : '', qty: Number(qty) || 1 };
      }
      if (entry && typeof entry === 'object' && typeof entry.handle === 'string') {
        // legacy object (pre-2026-10-06): name stored inline
        return { name: entry.name || nameFor(entry.handle), handle: entry.handle, size: typeof entry.size === 'string' ? entry.size : '', qty: Number(entry.qty) || 1 };
      }
      return null;
    })
    .filter(Boolean);
}

// True when the metadata carries an item list in either format (so callers can
// distinguish "no items recorded" from "items present but empty").
export function hasItems(metadata) {
  return typeof metadata?.[ITEMS_KEY] === 'string' && metadata[ITEMS_KEY] !== '';
}

// "SS Race Jersey (Men's M) ×2, Arm Warmers (M)" — the human summary used for
// metadata.product, the dashboard feed, and the Evri "Contents" column.
// Truncates on line boundaries with " … +N more" so it always fits `max`.
export function summariseItems(lines, max = METADATA_VALUE_MAX) {
  const parts = lines.map((i) => `${i.name || nameFor(i.handle)}${i.size ? ` (${i.size})` : ''}${(i.qty ?? i.quantity) > 1 ? ` ×${i.qty ?? i.quantity}` : ''}`);
  return joinWithin(parts, max, (n) => ` … +${n} more`);
}

// "Sizes: SS Race Jersey — Men's M, …" for the Stripe page's submit note.
export function sizesNote(lines, suffix = '', max = CUSTOM_TEXT_MAX) {
  const parts = lines.map((i) => `${i.name || nameFor(i.handle)} — ${i.size}`);
  const budget = max - 'Sizes: '.length - suffix.length;
  return 'Sizes: ' + joinWithin(parts, budget, (n) => ` … and ${n} more items`) + suffix;
}

// Join `parts` with ", " keeping within `max` characters; when it would
// overflow, drop trailing parts and append `tail(dropped)`.
function joinWithin(parts, max, tail) {
  const full = parts.join(', ');
  if (full.length <= max) return full;
  for (let keep = parts.length - 1; keep >= 1; keep--) {
    const candidate = parts.slice(0, keep).join(', ') + tail(parts.length - keep);
    if (candidate.length <= max) return candidate;
  }
  return (parts[0] || '').slice(0, Math.max(0, max - 1)) + '…';
}
